on:
  workflow_dispatch:
  push:
    tags:
      - "*"
name: demo
concurrency:
  group: demo
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install vercel cli
        run: npm install --global vercel@latest
      - name: vercel build
        run: vercel build --local-config demo/vercel.json --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: vercel deploy
        run: vercel deploy --local-config demo/vercel.json --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
