on:
  workflow_dispatch:
  push:
    tags:
      - "*"
name: release
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: cicd app auth
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: configure git
        run: |
          git config --global user.name "svelte5-router[bot]"
          git config --global user.email "svelte5-router[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app.outputs.token }}@github.com/${{ github.repository }}.git
      - name: install
        run: npm install
      - name: build
        run: npm run build
  test:
    needs: build
    permissions:
      id-token: write
      pages: write
    uses: ./.github/workflows/test.yaml
  notify:
    if: always()
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          status: ${{ needs.build.result }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
