name: "Publish documentation"
on:
  push:
    branches:
      - "main"
jobs:
  publish-documentation:
    permissions:
      id-token: "write"
      pages: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        name: "Check out Git repository"
        uses: "actions/checkout@v4"
      - id: "install-dependencies"
        name: "Install Node.js dependencies"
        run: npm install
      - id: "build"
        name: "Build documentation"
        run: npm run docs
      - id: "upload-documentation"
        name: "Upload Pages artifact"
        uses: "actions/upload-pages-artifact@v3.0.1"
        with:
          path: "tmp/typedoc"
      - id: "deployment"
        name: "Deploy documentation to GitHub Pages"
        uses: "actions/deploy-pages@v4.0.5"
