name: 📚 Docs
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - "*"
permissions:
  id-token: write
  pages: write
jobs:
  setup:
    name: 🔧 Request
    uses: ./.github/workflows/setup.yaml
  build:
    name: "📚 Build Docs"
    needs: setup
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
      - name: 📦 Hydrate node_modules
        uses: actions/cache@v3
        id: hydrate-node-modules
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}          
      - run: |
          ls -la
          npm list
      - name: Build documentation
        run: npm run docs:build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: tmp/build
      - id: deployment
        name: Deploy documentation to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
