name: publish api docs
on:
  workflow_dispatch:
  push:
    paths:
      - "docs/**"
      - "!docs/changelog.md"
      - "src/**"
    branches:
      - main
jobs:
  publish-documentation:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install Node.js dependencies
        run: npm install
      - name: Build documentation
        run: npm run docs:build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: tmp/build
      - id: deployment
        name: Deploy documentation to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
