name: 📚 Docs
on:
  workflow_dispatch:
  workflow_call:
permissions:
  id-token: write
  pages: write
defaults:
  run:
    shell: bash
    working-directory: ./docs
jobs:
  setup:
    name: 🔧 Request
    uses: ./.github/workflows/setup.yaml
  build:
    name: "📚 Build Docs"
    needs: setup
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # [setup] checkout the repo.
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      # [setup] setup node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.x
      - name: 📊 Generate diagrams
        run: make diagrams
      - name: 📚 Build documentation
        run: npm run docs:build
      - name: 📤 Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: tmp/build
      - id: deployment
        name: 📤 Deploy documentation to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
      # [setup] authenticate with the cicd app to get proper credentials for pushing to the repo later.
      - name: cicd app auth
        id: app
        uses: actions/create-github-app-token@v2.1.1
        with:
          app-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
      # [setup] configure git for later changelog generation, commit, and the finalpush.
      - name: 🔧 Commit and push diagrams
        run: |
          git config --global user.name "mateothegreat[bot]"
          git config --global user.email "mateothegreat[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app.outputs.token }}@github.com/${{ github.repository }}.git
          git add .
          git commit -am "chore(docs): update diagrams"
          git push origin HEAD:main
