on:
  push:
    paths-ignore:
      - "test/**"
      - "**/*.md"
    branches:
      - main
name: publish
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: cicd app auth
        id: app
        uses: actions/create-github-app-token@v1
        with:
            app-id: ${{ secrets.CICD_APP_ID }}
            private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
            token: ${{ steps.app.outputs.token }}
      - name: automated version bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: main
          commit-message: "CI: bumps version to {{version}} [skip ci]"
      - name: write to .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
      - name: install
        run: npm install --legacy-peer-deps
      - name: build
        run: npm run build
      - name: release
        run: npm run release