on:
  push:
    paths-ignore:
      - docs
      - test
    branches:
      - main
name: release
permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cicd app auth
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: generate changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: docs/changelog.md
          GITHUB_REPO: ${{ github.repository }}
      - name: bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
      - name: configure git
        run: |
          git config --global credential.helper store
          echo "https://x-access-token:${{ steps.app.outputs.token }}@github.com" > ~/.git-credentials
          git config --global user.name "svelte5-router[bot]"
          git config --global user.email "svelte5-router[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app.outputs.token }}@github.com/${{ github.repository }}.git
      - name: create and push changes to release branch
        run: |
          git checkout -b release/${{ steps.tag.outputs.new_tag }}
          git add .
          git commit -am "chore: update changelog and bumping package.json"
          git push origin release/${{ steps.tag.outputs.new_tag }}
      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.app.outputs.token }}
          branch: release/${{ steps.tag.outputs.new_tag }}
          title: "chore: release ${{ steps.tag.outputs.new_tag }}"
          body: "Automated release PR for version ${{ steps.tag.outputs.new_tag }}"
          labels: release
      - name: enable auto-merge
        run: |
          PR_NUMBER=$(gh pr list --head release/${{ steps.tag.outputs.new_tag }} --json number -q '.[0].number')
          gh pr merge $PR_NUMBER --auto --merge
        env:
          GH_TOKEN: ${{ steps.app.outputs.token }}
      - name: write to .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: release
        run: npm run release
      - name: publish
        run: npm publish
      - name: create github release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.git-cliff.outputs.changelog }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
  notify:
    if: always()
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          status: ${{ needs.build.result }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
