name: ⚡ Test Runner
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "**"
    tags:
      - "*"
permissions:
  contents: write
jobs:
  setup:
    name: "🔧 Setup"
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
          # cache-dependency-path: "package-lock.json"
      - name: 📥 Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps
      - run: npm list
  test:
    name: 🏃 Test
    needs: setup
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node (reuse cache from setup)
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Hydrate npm module cache
        uses: actions/cache@v3
        id: hydrate
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.hydrate.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps
      - run: npm list
      - name: 🔍 Run Tests
        run: npm run test:ci
      # Generate coverage badge from vitest coverage report.
      # https://github.com/marketplace/actions/vitest-badge-action
      - name: ⚙️ Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: "*"
          badges-icon: vitest
      - name: ⬆️ Push badges branch
        run: git push origin badges
