name: ⚡ Test Runner
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "**"
    tags:
      - "*"
permissions:
  contents: write
jobs:
  setup:
    name: "🔧 Setup"
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
          cache-dependency-path: ./package.json
      - name: 📥 Install Node.js dependencies
        run: npm install --legacy-peer-deps --no-package-lock
  test:
    name: 🏃 Test
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Check out repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
          cache-dependency-path: ./package.json
      - name: 📥 Install Node.js dependencies
        run: npm install --legacy-peer-deps --no-package-lock
      - name: 🔍 Run Tests
        run: npx vitest run --coverage src/lib/helpers/evaluators.test.ts
      # Generate coverage badge from vitest coverage report.
      # https://github.com/marketplace/actions/vitest-badge-action
      - name: ⚙️ Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: master,preprod,staging
          badges-icon: vitest
      - name: ⬆️ Push badges branch
        run: git push origin badges
