name: test
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "**"
    tags:
      - "*"
permissions:
  contents: write
jobs:
  test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install Node.js dependencies
        run: npm install --legacy-peer-deps --no-package-lock
      - name: Run Tests
        run: npx vitest run --coverage src/lib/helpers/evaluators.test.ts
      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure()
        with:
          result-type: statements
          upload-badge: false
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          summary-path: "tmp/coverage/coverage-summary.json"
          badge-text: "coverage"
          badge-path: "docs/assets/coverage-tests.svg"
